# 此时配置为开发环境
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 600MB
      max-request-size: 600MB
fdfs:
  connect-timeout: 1601
  so-timeout: 1501
  tracker-list: 1.15.227.166:22122

sso:
  clientId: Tp8uecHJi00aHlpufk8Fqp2A_2zpaKzS
  secret: f1Pm1ekcxfDWd3T6r7dluV-mfEi_Hh7f

